spring:
   datasource:
     url: jdbc:mysql://localhost:3306/loginauthenticationdb
     username: root
     password: password@12345
   jpa:
     hibernate:
       ddl-auto: update
       show-sql: true
app:
    authType: session
    cookie:
      login: cookie
    session:
      login: session

